# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import intrepidboats.apps.boats.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('show_image', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/')),
                ('base', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/')),
                ('hull', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/')),
                ('boot_stripe', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/')),
                ('boot_stripe_accent', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/')),
                ('sheer_stripe', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/')),
                ('sheer_stripe_accent', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
