# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_motor_motorinboat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorinboat',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='boats.Boat'),
        ),
    ]
