# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_auto_20170106_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorinboat',
            options={'verbose_name': 'motor in boat', 'verbose_name_plural': 'motors in boat'},
        ),
    ]
