# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_auto_20170112_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='show_image',
        ),
        migrations.AddField(
            model_name='boat',
            name='beam',
            field=models.CharField(default='', max_length=255, verbose_name='bean'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='length',
            field=models.CharField(default='', max_length=255, verbose_name='length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='standard_fuel',
            field=models.CharField(default='', max_length=255, verbose_name='standard fuel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='boats_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='boat',
            name='water',
            field=models.CharField(default='', max_length=255, verbose_name='water'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boat',
            name='model_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boats', to='boats.BoatModelGroup', verbose_name='model group'),
        ),
    ]
