# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:20
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import intrepidboats.apps.boats.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_auto_20170116_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('kind', models.CharField(choices=[('TOP', 'top'), ('ANCHOR', 'anchor'), ('BOW_RAIL', 'bow rail'), ('RUB_RAIL', 'rub rail'), ('REAR_CLOSEOUT', 'rear closeout'), ('DIVE_DOOR', 'dive door'), ('PORT_LIGHTS', 'port lights'), ('SS_RUB_RAIL_INSERT', 'ss rub rail insert')], default='TOP', max_length=25, verbose_name='kind')),
                ('available', models.BooleanField(default=False, verbose_name='available')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to='other_features/', verbose_name='image')),
                ('default', models.BooleanField(default=False, verbose_name='default')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='boats.Feature')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='MotorColorOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/', verbose_name='image')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=10)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='MotorSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'motor selection',
                'verbose_name_plural': 'motors selection',
            },
        ),
        migrations.RemoveField(
            model_name='motorinboat',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='motorinboat',
            name='motor',
        ),
        migrations.AddField(
            model_name='boat',
            name='logo',
            field=intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/', verbose_name='logo'),
        ),
        migrations.DeleteModel(
            name='MotorInBoat',
        ),
        migrations.AddField(
            model_name='motorselection',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_selections', to='boats.Boat', verbose_name='boat'),
        ),
        migrations.AddField(
            model_name='motorselection',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.Motor', verbose_name='motor'),
        ),
        migrations.AddField(
            model_name='motorcoloroption',
            name='motor_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='boats.MotorSelection', verbose_name='motor selection'),
        ),
        migrations.AddField(
            model_name='feature',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='boats.Boat'),
        ),
    ]
