# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0007_auto_20170120_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltBoatEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image_url', models.TextField(verbose_name='image url')),
                ('image', models.ImageField(upload_to='built_boats/', verbose_name='image')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('contact_sales', models.BooleanField(default=False, verbose_name='contact sales')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.Boat', verbose_name='boat')),
            ],
            options={
                'verbose_name': 'built boat email',
                'verbose_name_plural': 'built boat emails',
            },
        ),
        migrations.CreateModel(
            name='BuiltBoatShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image_url', models.TextField(verbose_name='image url')),
                ('image', models.ImageField(upload_to='built_boats/', verbose_name='image')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.Boat', verbose_name='boat')),
            ],
            options={
                'verbose_name': 'built boat share',
                'verbose_name_plural': 'built boat shares',
            },
        ),
    ]
