# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0008_builtboatemail_builtboatshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureoption',
            name='display_value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='display value'),
        ),
    ]
