# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import intrepidboats.apps.boats.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0010_auto_20170125_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', intrepidboats.apps.boats.fields.BoatImageField(blank=True, null=True, upload_to='boat_images/', verbose_name='image')),
                ('boat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck_plan', to='boats.Boat', verbose_name='boat')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
