# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_deckplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='boat_images/optionals/', verbose_name='thumbnail')),
                ('boat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_equipments', to='boats.Boat', verbose_name='boat model')),
            ],
            options={
                'verbose_name_plural': 'optional equipments',
                'verbose_name': 'optional equipment',
            },
        ),
    ]
