# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 14:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_deckplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatGeneralFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_features', to='boats.Boat', verbose_name='boat')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
        ),
    ]
