# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0013_merge_20170202_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalequipment',
            name='vimeo_id',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='vimeo ID'),
        ),
    ]
