# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0015_abouttheboat_abouttheboatimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_video_code', models.CharField(help_text='Add the ID that appears in the video url. Example: https://vimeo.com/123456, the code is 123456.', max_length=255, verbose_name='vimeo video code')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='boats.Boat', verbose_name='boat')),
            ],
        ),
    ]
