# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import intrepidboats.apps.boats.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0016_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttheboatimage',
            name='image',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='base',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='base'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='boot_stripe',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='boot stripe'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='boot_stripe_accent',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='boot stripe accent'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='hull',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='hull'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='logo',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sheer_stripe',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='sheer stripe'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sheer_stripe_accent',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='sheer stripe accent'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='thumbnail',
            field=models.ImageField(upload_to='boats_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='boatmodelgroup',
            name='show_image',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='show image'),
        ),
        migrations.AlterField(
            model_name='deckplan',
            name='image',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='image',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='motorcoloroption',
            name='image',
            field=intrepidboats.apps.boats.fields.BoatImageField(upload_to='boat_images/', verbose_name='image'),
        ),
    ]
