# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 14:20
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0017_auto_20170303_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcoloroption',
            name='color2',
            field=colorfield.fields.ColorField(blank=True, max_length=10, null=True),
        ),
    ]
