# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0019_auto_20170321_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttheboat',
            name='virtual_tour_link',
            field=models.URLField(blank=True, null=True, verbose_name='virtual_tour_link'),
        ),
    ]
