# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0020_abouttheboat_virtual_tour_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttheboat',
            name='virtual_tour_link',
            field=models.URLField(blank=True, null=True, verbose_name='virtual tour link'),
        ),
    ]
