# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0021_auto_20170323_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'ordering': ['title'], 'verbose_name': 'boat model', 'verbose_name_plural': 'boat models'},
        ),
        migrations.AlterField(
            model_name='boat',
            name='sheer_stripe',
            field=models.ImageField(blank=True, null=True, upload_to='boat_images/', verbose_name='sheer stripe'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sheer_stripe_accent',
            field=models.ImageField(blank=True, null=True, upload_to='boat_images/', verbose_name='sheer stripe accent'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='kind',
            field=models.CharField(choices=[('TOP', 'top'), ('ANCHOR', 'anchor'), ('BOW_RAIL', 'bow rail'), ('RUB_RAIL', 'rub rail'), ('REAR_CLOSEOUT', 'rear closeout'), ('DIVE_DOOR', 'dive door'), ('PORT_LIGHTS', 'port lights'), ('SS_RUB_RAIL_INSERT', 'rub rail insert')], default='TOP', max_length=25, verbose_name='kind'),
        ),
    ]
