# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0021_auto_20170323_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='boat_video_thumbnails/', verbose_name='thumbnail'),
        ),
    ]
