# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0022_auto_20170329_1113'),
        ('boats', '0022_auto_20170329_1036'),
    ]

    operations = [
    ]
