# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0023_merge_20170329_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_external_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='video external url'),
        ),
    ]
