# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0024_video_video_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='boats.Boat', verbose_name='boat'),
        ),
    ]
