# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0024_video_video_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckPlanHotspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('text', models.TextField(verbose_name='Popover content')),
                ('top_percentage', models.DecimalField(decimal_places=4, max_digits=7, verbose_name="'top' css attribute")),
                ('left_percentage', models.DecimalField(decimal_places=4, max_digits=7, verbose_name="'left' css attribute")),
                ('deck_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.DeckPlan', verbose_name='Deck plan')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
    ]
