# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0025_deckplanhotspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckplanhotspot',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Popover content'),
        ),
    ]
