# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0025_auto_20170518_1334'),
        ('boats', '0025_auto_20170517_0938'),
    ]

    operations = [
    ]
