# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0026_merge_20170522_1424'),
        ('boats', '0026_auto_20170512_0904'),
    ]

    operations = [
    ]
