# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0029_auto_20170612_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatGeneralFeatureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='boat_images/general_features/', verbose_name='thumbnail')),
                ('vimeo_id', models.CharField(blank=True, max_length=31, null=True, verbose_name='vimeo ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='boatgeneralfeature',
            name='description',
        ),
        migrations.AddField(
            model_name='boatgeneralfeatureitem',
            name='boat_general_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.BoatGeneralFeature'),
        ),
    ]
