# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageasset',
            options={'ordering': ['is_last']},
        ),
        migrations.AddField(
            model_name='pagesetting',
            name='preferred_assets_len',
            field=models.IntegerField(default=3),
        ),
    ]
