# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170104_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='is subscribed')),
            ],
            options={
                'verbose_name': 'newsletter subscriber',
                'verbose_name_plural': 'newsletter subscribers',
            },
        ),
    ]
