# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='is_subscribed',
        ),
    ]
