# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_newslettersubscriber_is_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageasset',
            options={'ordering': ['is_last'], 'verbose_name': 'page asset', 'verbose_name_plural': 'page assets'},
        ),
        migrations.AlterModelOptions(
            name='pagesetting',
            options={'verbose_name': 'page setting', 'verbose_name_plural': 'page settings'},
        ),
        migrations.AlterField(
            model_name='pageasset',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='pageasset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_settings/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='pageasset',
            name='is_last',
            field=models.BooleanField(default=False, verbose_name='is last'),
        ),
        migrations.AlterField(
            model_name='pageasset',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='common.PageSetting', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='pageasset',
            name='vimeo_video_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='vimeo video code'),
        ),
        migrations.AlterField(
            model_name='pagesetting',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pagesetting',
            name='preferred_assets_len',
            field=models.IntegerField(default=3, verbose_name='preferred_assets_len'),
        ),
    ]
