# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170119_0853'),
        ('common', '0008_extrauserdata'),
    ]

    operations = [
    ]
