# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20170130_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauserdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='auth/profile_pictures/', verbose_name='Image'),
        ),
    ]
