# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_extrauserdata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='auth/profile_pictures/', verbose_name='Profile picture'),
        ),
    ]
