# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20170206_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 17, 39, 27, 422637, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.URLField(default='http://www.miamiboatshow.com/', verbose_name='External link'),
            preserve_default=False,
        ),
    ]
