# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20170209_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',)},
        ),
    ]
