# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20170220_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageasset',
            name='video_external_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='video external url'),
        ),
    ]
