# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 15:32
from __future__ import unicode_literals

from django.db import migrations

from intrepidboats.apps.common.utils import get_external_url


def update_video_external_url(apps, schema_editor):
    PageAsset = apps.get_model('common', 'PageAsset')
    for page_asset in PageAsset.objects.all():
        if page_asset.vimeo_video_code:
            page_asset.video_external_url = get_external_url(page_asset.vimeo_video_code)
            page_asset.save()


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0015_pageasset_video_external_url'),
    ]

    operations = [
        migrations.RunPython(update_video_external_url)
    ]
