# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_extrauserdata_gallery_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageasset',
            options={'ordering': ['is_last', 'is_second_to_last'], 'verbose_name': 'page asset', 'verbose_name_plural': 'page assets'},
        ),
        migrations.AddField(
            model_name='pageasset',
            name='is_second_to_last',
            field=models.BooleanField(default=False, verbose_name='is second to last'),
        ),
    ]
