# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20170330_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
    ]
