# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20170424_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=100, verbose_name='Page title')),
            ],
        ),
    ]
