# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_sitemetadata_create_only_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemetadata',
            options={'verbose_name': 'Site metadata', 'verbose_name_plural': 'Site metadata'},
        ),
    ]
