# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20170512_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemetadata',
            name='all_models_description',
            field=models.CharField(default='Craftmanship and design that follow an uncompromising set of specifications. Yours.', max_length=1000, verbose_name='All models: Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='all_models_og_description',
            field=models.CharField(default='Craftmanship and design that follow an uncompromising set of specifications. Yours.', max_length=1000, verbose_name='All models: open graph: description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='all_models_og_title',
            field=models.CharField(default='All models - Intrepid Powerboats', max_length=100, verbose_name='All models: open graph: title'),
            preserve_default=False,
        ),
    ]
