# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20170512_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemetadata',
            name='careers_description',
            field=models.CharField(max_length=1000, verbose_name='Careers: Description'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='careers_og_description',
            field=models.CharField(max_length=1000, verbose_name='Careers: open graph: description'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='careers_og_title',
            field=models.CharField(max_length=100, verbose_name='Careers: open graph: title'),
        ),
    ]
