# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('common', '0028_auto_20170512_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPageMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=100, verbose_name='Page title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('og_title', models.CharField(max_length=100, verbose_name='Open graph: title')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site_metadata/', verbose_name='Open graph: image')),
                ('og_description', models.CharField(max_length=1000, verbose_name='Open graph: description')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_field', to='cms.Page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'CMS page metadata',
                'verbose_name_plural': 'CMS page metadata',
            },
        ),
    ]
