# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_cmspagemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspagemetadata',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='cms.Page', verbose_name='Page'),
        ),
    ]
