# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20170516_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemetadata',
            name='all_models_description',
        ),
        migrations.RemoveField(
            model_name='sitemetadata',
            name='all_models_og_description',
        ),
        migrations.RemoveField(
            model_name='sitemetadata',
            name='all_models_og_title',
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='owners_portal_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Owner's portal: Description"),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='owners_portal_og_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Owner's portal: open graph: description"),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='owners_portal_og_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Owner's portal: open graph: title"),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='careers_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Careers: Description'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='careers_og_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Careers: open graph: description'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='careers_og_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Careers: open graph: title'),
        ),
    ]
