# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20170516_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemetadata',
            name='careers_description',
        ),
        migrations.RemoveField(
            model_name='sitemetadata',
            name='careers_og_description',
        ),
        migrations.RemoveField(
            model_name='sitemetadata',
            name='careers_og_title',
        ),
    ]
