# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20170516_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemetadata',
            name='events_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Owner's portal: Description"),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='events_og_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Owner's portal: open graph: description"),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='events_og_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Owner's portal: open graph: title"),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='whats_new_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Owner's portal: Description"),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='whats_new_og_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Owner's portal: open graph: description"),
        ),
        migrations.AddField(
            model_name='sitemetadata',
            name='whats_new_og_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Owner's portal: open graph: title"),
        ),
    ]
