# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_auto_20170516_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemetadata',
            name='events_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Events: Description'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='events_og_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Events: open graph: description'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='events_og_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Events: open graph: title'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='whats_new_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="What's new: Description"),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='whats_new_og_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="What's new: open graph: description"),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='whats_new_og_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="What's new: open graph: title"),
        ),
    ]
