# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='boats.Video'),
        ),
    ]
