# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_auto_20170517_1007'),
        ('common', '0036_auto_20170516_1517'),
    ]

    operations = [
    ]
