# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-18 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_extrauserdata_phone'),
        ('common', '0038_merge_20170518_1036'),
    ]

    operations = [
    ]
