# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_extrauserdata_own_intrepid'),
        ('common', '0040_merge_20180318_0906'),
    ]

    operations = [
    ]
