# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_conversation', '0009_auto_20160925_2126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_remove_forum_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('old_forum_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('row_data', models.TextField()),
                ('forum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('old_topic_id', models.IntegerField()),
                ('old_post_id', models.IntegerField()),
                ('old_poster_id', models.IntegerField(blank=True, null=True)),
                ('old_username', models.CharField(blank=True, max_length=255, null=True)),
                ('old_posted_at', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('row_data', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum_conversation.Post')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('old_forum_id', models.IntegerField()),
                ('old_topic_id', models.IntegerField()),
                ('old_poster_id', models.IntegerField()),
                ('is_deleted', models.CharField(max_length=10)),
                ('views_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('row_data', models.TextField()),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum_conversation.Topic')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('old_user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('row_data', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
    ]
