# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoRateLimiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_time', models.DateTimeField(verbose_name='reset time')),
                ('remaining_requests', models.IntegerField(verbose_name='remaining requests')),
            ],
        ),
    ]
