# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('difference', '0002_testimonialvideoplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrepidDifferenceSectionPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='difference_intrepiddifferencesectionplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('section_text', models.TextField(verbose_name='Section Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
