# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 15:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0005_sharedtestimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrepiddifferencesectionplugin',
            name='section_text',
            field=ckeditor.fields.RichTextField(verbose_name='Section Text'),
        ),
        migrations.AlterField(
            model_name='testimonialplugin',
            name='extra_paragraphs',
            field=ckeditor.fields.RichTextField(verbose_name='Extra paragraphs'),
        ),
        migrations.AlterField(
            model_name='testimonialplugin',
            name='first_paragraph',
            field=ckeditor.fields.RichTextField(verbose_name='First paragraph'),
        ),
    ]
