# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0005_sharedtestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTestimonialUploadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ticket_id', models.CharField(max_length=610, verbose_name='ticket id')),
                ('uri', models.CharField(max_length=255, verbose_name='uri')),
                ('vimeo_user', models.TextField(verbose_name='vimeo user')),
                ('upload_link_secure', models.CharField(max_length=610, verbose_name='upload link secure')),
                ('complete_uri', models.CharField(max_length=610, verbose_name='complete uri')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
            ],
            options={
                'verbose_name': 'shared testimonial info',
            },
        ),
        migrations.AddField(
            model_name='sharedtestimonial',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_testimonial', to='difference.SharedTestimonialUploadInfo', verbose_name='upload information'),
        ),
    ]
