# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0006_auto_20170120_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialplugin',
            name='extra_paragraphs',
        ),
        migrations.RemoveField(
            model_name='testimonialplugin',
            name='first_paragraph',
        ),
        migrations.RemoveField(
            model_name='testimonialplugin',
            name='title',
        ),
        migrations.AddField(
            model_name='sharedtestimonial',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonialplugin',
            name='testimonial',
            field=models.ManyToManyField(to='difference.SharedTestimonial'),
        ),
    ]
