# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0006_auto_20170120_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedtestimonialuploadinfo',
            options={'verbose_name': 'shared testimonial info', 'verbose_name_plural': 'shared testimonial info'},
        ),
        migrations.AlterField(
            model_name='sharedtestimonial',
            name='file',
            field=models.FileField(null=True, upload_to='shared_testimonials/', verbose_name='file'),
        ),
    ]
