# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0006_auto_20170120_1024'),
        ('difference', '0007_auto_20170124_0946'),
    ]

    operations = [
    ]
