# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0008_auto_20170125_1318'),
        ('difference', '0008_merge_20170126_0723'),
    ]

    operations = [
    ]
