# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0009_merge_20170126_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedtestimonial',
            name='approved',
        ),
    ]
