# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0010_remove_sharedtestimonial_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrepiddifferencesectionplugin',
            name='image',
            field=models.ImageField(blank=True, upload_to='cms/', verbose_name='Image'),
        ),
    ]
