# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0011_auto_20170130_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtestimonial',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_testimonial', to='difference.SharedTestimonialUploadInfo', verbose_name='upload information'),
        ),
    ]
