# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 17:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('difference', '0012_auto_20170207_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithTextPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='difference_imagewithtextplugin', serialize=False, to='cms.CMSPlugin')),
                ('image', models.ImageField(upload_to='cms/', verbose_name='Image')),
                ('section_text', ckeditor.fields.RichTextField(verbose_name='Section Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
