# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0013_imagewithtextplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithtextplugin',
            name='section_text',
            field=models.TextField(verbose_name='Section Text'),
        ),
    ]
