# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0014_auto_20170306_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtestimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='owners_gallery/', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='sharedtestimonial',
            name='video_id',
            field=models.CharField(max_length=127, null=True, verbose_name='video id'),
        ),
    ]
