# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0015_auto_20170316_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtestimonial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='shared_testimonials/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='sharedtestimonial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sharedtestimonial',
            name='video_id',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='video id'),
        ),
    ]
