# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0016_auto_20170327_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithtextplugin',
            name='section_text',
            field=models.TextField(blank=True, null=True, verbose_name='Section Text'),
        ),
    ]
