# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0017_auto_20170516_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrepiddifferencesectionplugin',
            name='image',
        ),
    ]
