# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0014_optionalequipment_vimeo_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners_portal', '0002_auto_20170112_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('manual', models.FileField(blank=True, null=True, upload_to='boat_manuals/', verbose_name='manual')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='BoatPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='BoatStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='owners_portal.BoatPhase')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoatStepAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(upload_to='boat_designs/step_images/')),
                ('vimeo_video_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='vimeo video code')),
                ('boat_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='owners_portal.BoatStep')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='StepFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comments', models.TextField(verbose_name='comments')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners_portal.BoatStep', verbose_name='step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='UserBoat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('design', models.ImageField(upload_to='boat_designs/', verbose_name='design')),
                ('notes', models.TextField(blank=True, default='', null=True, verbose_name='notes')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.Boat', verbose_name='boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_boats', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='boatstep',
            name='user_boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='owners_portal.UserBoat'),
        ),
        migrations.AddField(
            model_name='boatmanual',
            name='user_boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='owners_portal.UserBoat'),
        ),
    ]
