# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0003_auto_20170206_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboat',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.Boat', verbose_name='boat model'),
        ),
    ]
