# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners_portal', '0004_auto_20170209_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.RemoveField(
            model_name='sharedvideo',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='sharedvideo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sharedvideo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sharedvideo',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='sharedvideo',
            name='uploader',
        ),
        migrations.CreateModel(
            name='SharedPicture',
            fields=[
                ('sharedmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='owners_portal.SharedMedia')),
                ('image', models.ImageField(upload_to='shared_images/')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=('owners_portal.sharedmedia',),
        ),
        migrations.AddField(
            model_name='sharedmedia',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_media', to=settings.AUTH_USER_MODEL, verbose_name='uploader'),
        ),
        migrations.AddField(
            model_name='sharedvideo',
            name='sharedmedia_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='owners_portal.SharedMedia'),
            preserve_default=False,
        ),
    ]
