# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('owners_portal', '0005_auto_20170220_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedmedia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sharedpicture',
            options={'verbose_name': 'shared picture', 'verbose_name_plural': 'shared pictures'},
        ),
        migrations.AddField(
            model_name='sharedmedia',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_owners_portal.sharedmedia_set+', to='contenttypes.ContentType'),
        ),
    ]
