# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0006_auto_20170222_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmedia',
            name='is_public',
            field=models.BooleanField(choices=[(True, 'Share with the whole community'), (False, 'Keep it private')], default=False, verbose_name='is public'),
        ),
    ]
