# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0007_auto_20170224_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedvideo',
            name='video_id',
            field=models.CharField(max_length=127, null=True, verbose_name='video id'),
        ),
    ]
