# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0009_sharedvideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='owners_gallery/', verbose_name='thumbnail'),
        ),
    ]
