# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0011_auto_20170316_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmedia',
            name='is_public',
            field=models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False, verbose_name='is public'),
        ),
    ]
