# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 13:27
from __future__ import unicode_literals

from django.db import migrations

from intrepidboats.apps.common.utils import get_external_url


def update_video_external_url(apps, schema_editor):
    SharedVideo = apps.get_model('owners_portal', 'SharedVideo')
    for video in SharedVideo.objects.all():
        if video.video_id:
            video.video_external_url = get_external_url(video.video_id)
            video.save()


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0013_auto_20170327_0924'),
    ]

    operations = [
        migrations.RunPython(update_video_external_url)
    ]
