# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0015_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatmanual',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='boat_manual_video_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='boatmanual',
            name='vimeo_video_code',
            field=models.CharField(blank=True, help_text='Add the ID that appears in the video url. Example: https://vimeo.com/123456, the code is 123456.', max_length=255, null=True, verbose_name='vimeo video code'),
        ),
    ]
