# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0016_auto_20170711_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatmanual',
            name='thumbnail',
        ),
    ]
