# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0020_remove_boatmanual_user_boat'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatmanual',
            name='video_external_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='video external url'),
        ),
    ]
