# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0021_boatmanual_video_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatmanual',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description for Facebook share'),
        ),
        migrations.AddField(
            model_name='boatmanual',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='owners_gallery/manual_thumbnails/', verbose_name='Thumbnail for Facebook share'),
        ),
    ]
