# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0022_auto_20170712_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatmanual',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners_portal.BoatManualGroup'),
        ),
    ]
