# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-18 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners_portal', '0023_auto_20170712_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boatmanual',
            options={'verbose_name': 'user boat manual'},
        ),
        migrations.AlterModelOptions(
            name='boatmanualgroup',
            options={'verbose_name': 'user boat manuals', 'verbose_name_plural': 'user boat manuals'},
        ),
        migrations.AlterModelManagers(
            name='sharedpicture',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sharedvideo',
            managers=[
            ],
        ),
    ]
